syntax = "proto3";

package volta;

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";

import "./types/transport.proto";
import "./types/common.proto";

option go_package = "server/pb;pb";

service VoltaCollector {
  // Bidirectional streaming RPC that remains open for the lifetime of the connection.
  // Exchanges control messages between the server and the agent.
  // Primarily used for pings and server requests that instruct the agent to send data.
  rpc Connect(stream ControlMessage) returns (stream ControlMessage);

  // Client streaming RPC that allows the agent to send a stream of metrics to the server.
  rpc StreamData(stream Metric) returns (google.protobuf.Empty);
}