syntax = "proto3";

import "google/protobuf/timestamp.proto";

package volta;

option go_package = "server/generated/volta;volta";

service VoltaCollector {
  // Bidirectional streaming RPC that remains open for the lifetime of the connection.
  // Exchanges control messages between the server and the agent.
  // Primarily used for server requests that instruct the agent to send data.
  rpc Connect(stream ControlMessage) returns (stream ControlMessage);
}

message ControlMessage {
    MessageType type = 1;
    string payload = 2;
}

enum MessageType {
    UNKNOWN = 0;
    SEND_DATA = 1;
    OK = 2;
    ERROR = 3;
    PING = 4;
    PONG = 5;
}