name: Agent CI

on:
  push:
    branches: [ "main", "devel" ]
    paths:
      - 'sources/agent/src/**'
      - 'sources/agent/libs/**'
      - 'sources/agent/CMakeLists.txt'
      - 'sources/agent/vcpkg.json'
      - 'sources/agent/CMakePresets.json'
      - '.github/workflows/agent_ci.yml'
  pull_request:
    branches: [ "main", "devel" ]
    paths:
      - 'sources/agent/src/**'
      - 'sources/agent/libs/**'
      - 'sources/agent/CMakeLists.txt'
      - 'sources/agent/vcpkg.json'
      - 'sources/agent/CMakePresets.json'
      - '.github/workflows/agent_ci.yml'

jobs:
  build-and-test:
    name: Build & Format Check
    runs-on: ubuntu-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v4


    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang-format cppcheck

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'sources/agent/vcpkg.json'

    - name: Check Code Formatting
      run: |
        find sources/agent -name "*.cc" -o -name "*.h" | xargs clang-format --dry-run --Werror -style=Google

    - name: CMake Configure
      working-directory: sources/agent
      run: cmake --preset default

    - name: Build
      working-directory: sources/agent
      run: cmake --build --preset default

    - name: Analyze Logic
      run: |
        cppcheck --enable=warning,performance,portability \
        --error-exitcode=1 \
        --suppress=missingIncludeSystem \
        --inline-suppr \
        --force \
        -i build \
        sources/agent
